""" 
Guessing game:
    programme choose a random number and the user
    try to guess that number in less than 3 attmepts!

    skills: 
        - type casting
        - loops
        - conditional statment
        - user input
"""
#import requrired module
import random  

attempts = 3                         #max no. of attempts   
rand_number = random.randint(1,10)   #random number generated by the program 

while attempts > 0: 
    user_guess = raw_input("Guess a number between 1 and 10 ")
    user_guess = int(user_guess)     #IMPORTANT! type casting (str-> int  )

    #conditional statementes 
    if user_guess == rand_number:
        print "WOW! you read my mind? Good boy!"
        break
    elif user_guess > rand_number:
        print "Good, but it's too high!"
    elif user_guess < rand_number:
        print "Sorry, it's too low"

    attempts -= 1